name: Auto-Release Tagging

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  tag:
    name: Generate Tag
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Create and Push Tag
        uses: mathieudutour/github-tag-action@v6.2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          # dry_run defaults to false, so it will automatically tag and push!
